-- MySQL Script generated by MySQL Workbench
-- Tue Jul 15 15:09:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema sistema-ganadero-recria
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_roles`),
  UNIQUE INDEX `nombres_UNIQUE` (`nombres` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `id_roles` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_usuarios_roles_idx` (`id_roles` ASC),
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_roles`)
    REFERENCES `roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `carnet_identidad` VARCHAR(45) NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ganadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ganadero` (
  `id_ganadero` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `tipo_ganadero` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_ganadero`),
  INDEX `fk_ganadero_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_ganadero_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `id_ganadero` INT NOT NULL,
  `marca` VARCHAR(100) NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `marca_UNIQUE` (`marca` ASC),
  INDEX `fk_marca_ganadero1_idx` (`id_ganadero` ASC),
  CONSTRAINT `fk_marca_ganadero1`
    FOREIGN KEY (`id_ganadero`)
    REFERENCES `ganadero` (`id_ganadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intermediario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intermediario` (
  `id_intermediario` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_intermediario`),
  INDEX `fk_intermediario_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_intermediario_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_transporte` (
  `id_tipo_transporte` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_tipo_transporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transportista` (
  `id_transportista` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `id_tipo_transporte` INT NOT NULL,
  `trayecto` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_transportista`),
  INDEX `fk_transportista_persona1_idx` (`id_persona` ASC),
  INDEX `fk_transportista_tipo_transporte1_idx` (`id_tipo_transporte` ASC),
  CONSTRAINT `fk_transportista_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transportista_tipo_transporte1`
    FOREIGN KEY (`id_tipo_transporte`)
    REFERENCES `tipo_transporte` (`id_tipo_transporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estancias` (
  `id_estancia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `departamento` VARCHAR(60) NULL,
  `referencia` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_estancia`),
  INDEX `fk_estancias_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_estancias_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos_cargos` (
  `id_tipos_cargos` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `area` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_tipos_cargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrato_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contrato_empleado` (
  `id_contrato_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_tipos_cargos` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `fecha_ingreso` DATE NULL,
  `fecha_salida` DATE NULL,
  `sueldo` FLOAT NULL,
  `afp_empleado` FLOAT NULL,
  `afp_empleador` FLOAT NULL,
  `caja_nacional` FLOAT NULL,
  `bono_antiguedad` FLOAT NULL,
  `sueldo_liquido` FLOAT NULL,
  `sueldo_total` FLOAT NULL,
  `forma_pago` FLOAT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_contrato_empleado`),
  INDEX `fk_contrato_empleado_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_contrato_empleado_tipo_contrato1_idx` (`id_tipos_cargos` ASC),
  CONSTRAINT `fk_contrato_empleado_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_empleado_tipo_contrato1`
    FOREIGN KEY (`id_tipos_cargos`)
    REFERENCES `tipos_cargos` (`id_tipos_cargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_pago` (
  `id_tipo_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleta_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boleta_pago` (
  `id_boleta_pago` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_pago` INT NOT NULL,
  `id_contrato_empleado` INT NOT NULL,
  `fecha` DATE NULL,
  `pago` FLOAT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_boleta_pago`),
  INDEX `fk_boleta_pago_tipo_pago1_idx` (`id_tipo_pago` ASC),
  INDEX `fk_boleta_pago_contrato_empleado1_idx` (`id_contrato_empleado` ASC),
  CONSTRAINT `fk_boleta_pago_tipo_pago1`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleta_pago_contrato_empleado1`
    FOREIGN KEY (`id_contrato_empleado`)
    REFERENCES `contrato_empleado` (`id_contrato_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gastos_fijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos_fijos` (
  `id_gastos_fijos` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_gastos_fijos`),
  INDEX `fk_gastos_fijos_usuarios1_idx` (`id_usuarios` ASC),
  CONSTRAINT `fk_gastos_fijos_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pago_gasto_fijo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pago_gasto_fijo` (
  `id_pago_gasto_fijo` INT NOT NULL AUTO_INCREMENT,
  `id_gastos_fijos` INT NOT NULL,
  `id_usuarios` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `total` FLOAT NULL,
  `fecha` DATE NULL,
  `mes_correspondiente` VARCHAR(50) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_pago_gasto_fijo`),
  INDEX `fk_pago_gasto_fijo_gastos_fijos1_idx` (`id_gastos_fijos` ASC),
  INDEX `fk_pago_gasto_fijo_usuarios1_idx` (`id_usuarios` ASC),
  INDEX `fk_pago_gasto_fijo_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_pago_gasto_fijo_gastos_fijos1`
    FOREIGN KEY (`id_gastos_fijos`)
    REFERENCES `gastos_fijos` (`id_gastos_fijos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_gasto_fijo_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_gasto_fijo_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_gastos_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_gastos_variables` (
  `id_tipo_gastos_variables` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_tipo_gastos_variables`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gastos_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos_variables` (
  `id_gastos_variables` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_gastos_variables` INT NOT NULL,
  `id_usuarios` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `total` FLOAT NULL,
  `descripcion` VARCHAR(120) NULL,
  `fecha` DATE NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_gastos_variables`),
  INDEX `fk_gastos_variables_tipo_gastos_variables1_idx` (`id_tipo_gastos_variables` ASC),
  INDEX `fk_gastos_variables_usuarios1_idx` (`id_usuarios` ASC),
  INDEX `fk_gastos_variables_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_gastos_variables_tipo_gastos_variables1`
    FOREIGN KEY (`id_tipo_gastos_variables`)
    REFERENCES `tipo_gastos_variables` (`id_tipo_gastos_variables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_variables_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_variables_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_gastos` (
  `id_detalle_gastos` INT NOT NULL AUTO_INCREMENT,
  `id_gastos_variables` INT NOT NULL,
  `cantidad` FLOAT NULL,
  `detalle` VARCHAR(100) NULL,
  `precio_unitario` FLOAT NULL,
  `sub_total` FLOAT NULL,
  PRIMARY KEY (`id_detalle_gastos`),
  INDEX `fk_detalle_gastos_gastos_variables1_idx` (`id_gastos_variables` ASC),
  CONSTRAINT `fk_detalle_gastos_gastos_variables1`
    FOREIGN KEY (`id_gastos_variables`)
    REFERENCES `gastos_variables` (`id_gastos_variables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_animales` (
  `id_venta_animales` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_estancia` INT NULL,
  `id_intermediario` INT NULL,
  `id_ganadero` INT NULL,
  `id_transportista` INT NULL,
  `fecha` DATE NULL,
  `total` FLOAT NULL,
  `comision` FLOAT NULL,
  `tipo_venta` VARCHAR(45) NULL,
  `estancia_destino` VARCHAR(100) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_venta_animales`),
  INDEX `fk_venta_animales_usuarios1_idx` (`id_usuarios` ASC),
  INDEX `fk_venta_animales_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_venta_animales_estancias1_idx` (`id_estancia` ASC),
  CONSTRAINT `fk_egresos_animales_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_egresos_animales_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_egresos_animales_estancias1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `estancias` (`id_estancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria_ingresos` (
  `id_categoria_ingresos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_categoria_ingresos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otros_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otros_ingresos` (
  `id_otros_ingresos` INT NOT NULL AUTO_INCREMENT,
  `id_categoria_ingresos` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_usuarios` INT NOT NULL,
  `fecha` DATE NULL,
  `forma_pago` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`id_otros_ingresos`),
  INDEX `fk_otros_ingresos_categoria_ingresos1_idx` (`id_categoria_ingresos` ASC),
  INDEX `fk_otros_ingresos_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_otros_ingresos_usuarios1_idx` (`id_usuarios` ASC),
  CONSTRAINT `fk_otros_ingresos_categoria_ingresos1`
    FOREIGN KEY (`id_categoria_ingresos`)
    REFERENCES `categoria_ingresos` (`id_categoria_ingresos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otros_ingresos_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otros_ingresos_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_ingresos` (
  `id_detalle_ingresos` INT NOT NULL AUTO_INCREMENT,
  `id_otros_ingresos` INT NOT NULL,
  `cantidad` DECIMAL NULL,
  `detalle` VARCHAR(45) NULL,
  `precio_unitario` FLOAT NULL,
  `sub_total` FLOAT NULL,
  PRIMARY KEY (`id_detalle_ingresos`),
  INDEX `fk_detalle_ingresos_otros_ingresos1_idx` (`id_otros_ingresos` ASC),
  CONSTRAINT `fk_detalle_ingresos_otros_ingresos1`
    FOREIGN KEY (`id_otros_ingresos`)
    REFERENCES `otros_ingresos` (`id_otros_ingresos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_animal` (
  `id_tipo_animal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `raza` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_tipo_animal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_animal` INT NOT NULL,
  `id_estancia` INT NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `stock` INT NULL,
  `categoria` VARCHAR(100) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_animal`),
  INDEX `fk_animal_tipo_animal1_idx` (`id_tipo_animal` ASC),
  INDEX `fk_animal_estancias1_idx` (`id_estancia` ASC),
  CONSTRAINT `fk_animal_tipo_animal1`
    FOREIGN KEY (`id_tipo_animal`)
    REFERENCES `tipo_animal` (`id_tipo_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_estancias1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `estancias` (`id_estancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra_animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra_animales` (
  `id_compra_animales` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_estancia` INT NOT NULL,
  `id_intermediario` INT NULL,
  `id_ganadero` INT NULL,
  `id_transportista` INT NULL,
  `fecha` DATE NULL,
  `total` FLOAT NULL,
  `comision` FLOAT NULL,
  `tipo_compra` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id_compra_animales`),
  INDEX `fk_compra_animales_usuarios1_idx` (`id_usuarios` ASC),
  INDEX `fk_compra_animales_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_compra_animales_estancias1_idx` (`id_estancia` ASC),
  CONSTRAINT `fk_compra_animales_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_animales_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_animales_estancias1`
    FOREIGN KEY (`id_estancia`)
    REFERENCES `estancias` (`id_estancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle_movimiento_animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_movimiento_animales` (
  `id_detalle_venta_animales` INT NOT NULL AUTO_INCREMENT,
  `id_animal` INT NOT NULL,
  `id_compra_animales` INT NULL,
  `id_venta_animales` INT NULL,
  `cantidad` INT NULL,
  `peso` FLOAT NULL,
  `tipo_movimiento` VARCHAR(100) NULL,
  `precio_unitario` FLOAT NULL,
  `sub_total` FLOAT NULL,
  `fecha` DATE NULL,
  `precio_transporte` DECIMAL NULL,
  `placa_camion` VARCHAR(10) NULL,
  PRIMARY KEY (`id_detalle_venta_animales`),
  INDEX `fk_detalle_venta_animales_animal1_idx` (`id_animal` ASC),
  INDEX `fk_detalle_venta_animales_venta_animales1_idx` (`id_venta_animales` ASC),
  INDEX `fk_detalle_movimiento_animales_compra_animales1_idx` (`id_compra_animales` ASC),
  CONSTRAINT `fk_detalle_venta_animales_animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_animales_venta_animales1`
    FOREIGN KEY (`id_venta_animales`)
    REFERENCES `venta_animales` (`id_venta_animales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_movimiento_animales_compra_animales1`
    FOREIGN KEY (`id_compra_animales`)
    REFERENCES `compra_animales` (`id_compra_animales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datos_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datos_empresa` (
  `id_datos_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `telefono` INT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id_datos_empresa`))
ENGINE = InnoDB;

